//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        public Pizza()
        {
            this.AddtoCarts = new HashSet<AddtoCart>();
        }
    
        public int PizzaID { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
        public int SmallPrice { get; set; }
        public int MediumPrice { get; set; }
        public int LargePrice { get; set; }
    
        public virtual ICollection<AddtoCart> AddtoCarts { get; set; }
    }
}
