//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        public int OrderID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> OrderTotal { get; set; }
        public string Status { get; set; }
        public int DeliveryID { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual DeliveryAddress DeliveryAddress { get; set; }
    }
}
